trigger:
  branches:
    include:
    - refs/heads/main
pr:
  branches:
    include:
    - main
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Angular build CI
  pool:
    name: Default
  steps:
  - task: NodeTool@0
    displayName: Use Node 18.x
    inputs:
      versionSpec: 18.x
  - task: Npm@1
    displayName: npm install
    inputs:
      workingDir: src
      verbose: false
  - task: Npm@1
    displayName: 'ng build'
    inputs:
      command: 'custom'
      customCommand: 'run ng build'

  - task: Npm@1
    displayName: 'install lighthouse'
    inputs:
      command: 'install'
      customCommand: '-g lighthouse'
  - task: Npm@1
    inputs:
      command: 'install'
      customCommand: 'install -g @lhci/cli@0.14.x'
    displayName: 'install lhci'
  - script: |
      lhci autorun --collect.staticDistDir=dist
    env:
      LHCI_GITHUB_APP_TOKEN: 'RN9p9l1UYcG0uORt:56737945:hS9QrbIG'
    displayName: 'Run Lighthouse Audit'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: dist
...
