trigger:
  branches:
    include:
    - refs/heads/main
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Angular build CI
  pool:
    name: Default
  steps:
  - task: NodeTool@0
    displayName: Use Node 16.x
    inputs:
      versionSpec: 16.x
  - task: Npm@1
    displayName: npm install
    inputs:
      workingDir: src
      verbose: false
  - task: Npm@1
    displayName: 'ng build'
    inputs:
      command: 'custom'
      customCommand: 'run ng build'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: dist
...
